const columns = [
  { name: "USER", uid: "user", sortable: true },
  { name: "START DATE", uid: "startDate", sortable: true },
  { name: "END DATE", uid: "endDate", sortable: true },
  { name: "START TIME", uid: "startTime", sortable: true },
  { name: "END TIME", uid: "endTime", sortable: true },
  { name: "DAY OF WEEK", uid: "dayOfWeek", sortable: true },
  { name: "APPROVED", uid: "approved", sortable: true },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Expired", uid: "expired" },
  { name: "Removed", uid: "removed" },
];

const approvedOptions = [
  { name: "Yes", uid: "yes" },
  { name: "No", uid: "no" },
];

const users = [
  {
    id: 1,
    user: "User A",
    startDate: "2022-01-01",
    endDate: "2022-01-31",
    startTime: "10:00",
    endTime: "18:00",
    dayOfWeek: "Monday",
    approved: "yes",
    status: "active",
  },
  {
    id: 2,
    user: "User B",
    startDate: "2022-02-01",
    endDate: "2022-02-28",
    startTime: "09:00",
    endTime: "17:00",
    dayOfWeek: "Tuesday",
    approved: "no",
    status: "expired",
  },
  {
    id: 3,
    user: "User C",
    startDate: "2022-03-01",
    endDate: "2022-03-31",
    startTime: "08:00",
    endTime: "16:00",
    dayOfWeek: "Wednesday",
    approved: "yes",
    status: "active",
  },
  {
    id: 4,
    user: "User D",
    startDate: "2022-04-01",
    endDate: "2022-04-30",
    startTime: "07:00",
    endTime: "15:00",
    dayOfWeek: "Thursday",
    approved: "no",
    status: "removed",
  },
  {
    id: 5,
    user: "User E",
    startDate: "2022-05-01",
    endDate: "2022-05-31",
    startTime: "06:00",
    endTime: "14:00",
    dayOfWeek: "Friday",
    approved: "yes",
    status: "active",
  },
  {
    id: 6,
    user: "User F",
    startDate: "2022-06-01",
    endDate: "2022-06-30",
    startTime: "05:00",
    endTime: "13:00",
    dayOfWeek: "Saturday",
    approved: "no",
    status: "expired",
  },
  {
    id: 7,
    user: "User G",
    startDate: "2022-07-01",
    endDate: "2022-07-31",
    startTime: "04:00",
    endTime: "12:00",
    dayOfWeek: "Sunday",
    approved: "yes",
    status: "removed",
  },
  {
    id: 8,
    user: "User H",
    startDate: "2022-08-01",
    endDate: "2022-08-31",
    startTime: "03:00",
    endTime: "11:00",
    dayOfWeek: "Monday",
    approved: "no",
    status: "active",
  },
  {
    id: 9,
    user: "User I",
    startDate: "2022-09-01",
    endDate: "2022-09-30",
    startTime: "02:00",
    endTime: "10:00",
    dayOfWeek: "Tuesday",
    approved: "yes",
    status: "expired",
  },
  {
    id: 10,
    user: "User J",
    startDate: "2022-10-01",
    endDate: "2022-10-31",
    startTime: "01:00",
    endTime: "09:00",
    dayOfWeek: "Wednesday",
    approved: "no",
    status: "removed",
  },
];

export { columns, users, statusOptions, approvedOptions };
